services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - C:\Docker\pgdata:/var/lib/postgresql
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
   